name: Node.js CI

on:
  push:
    branches:
      - backend

env:
  PORT: ${{ secrets.PORT }}
  NODE_ENV: ${{ secrets.NODE_ENV }}
  SALT_ROUNDS: ${{ secrets.SALT_ROUNDS }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  DB_URI_CLOUD: ${{ secrets.DB_URI_CLOUD }}
  API_KEY: ${{ secrets.API_KEY }}
  SENDER_ID: ${{ secrets.SENDER_ID }}

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      # # Set up Node.js for the project
      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '22'

      # Create the backend folder in /home if it doesn't exist
      - name: Create backend folder in /home
        run: sudo mkdir -p /home/naamist_backend

      # Copy the contents of NAAMIST to /home/naamist_backend
      - name: Copy NAAMIST folder
        run: sudo cp -r ../NAAMIST/* /home/naamist_backend

      # Set /home/naamist_backend as the default working directory
      - name: Install dependencies for backend
        working-directory: /home/naamist_backend
        run: npm ci

      # Start backend using PM2 from /home/naamist_backend
      - name: Start backend with PM2
        working-directory: /home/naamist_backend
        run: pm2 restart naamist -a
