name: Node.js CI

on:
  push:
    branches:
      - backend

env:
  PORT: ${{ secrets.PORT }}
  NODE_ENV: ${{ secrets.NODE_ENV }}
  SALT_ROUNDS: ${{ secrets.SALT_ROUNDS }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  DB_URI_CLOUD: ${{ secrets.DB_URI_CLOUD }}
  API_KEY: ${{ secrets.API_KEY }}
  SENDER_ID: ${{ secrets.SENDER_ID }}

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      # Set up Node.js for the project
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Create the backend folder if it doesn't exist
      - name: Create backend folder
        run: sudo mkdir -p ../naamist_backend

      # Copy the NAAMIST folder to the backend directory test
      - name: Copy NAAMIST folder
        run: sudo cp -r ../NAAMIST/* ../naamist_backend

      # Install dependencies for backend
      - name: Install dependencies for backend
        working-directory: ../naamist_backend
        run: npm ci

      # Start backend using PM2
      - name: Start backend with PM2
        working-directory: ../naamist_backend
        run: pm2 restart naamist -a
