name: Node.js CI

on:
  push:
    branches:
      - backend

env:
  PORT: ${{secrets.PORT}}
  NODE_ENV: ${{secrets.NODE_ENV}}
  SALT_ROUNDS: ${{secrets.SALT_ROUNDS}}
  JWT_SECRET: ${{secrets.JWT_SECRET}}
  DB_URI_CLOUD: ${{secrets.DB_URI_CLOUD}}
  API_KEY: ${{secrets.API_KEY}}
  SENDER_ID: ${{secrets.SENDER_ID}}

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      # Change the working directory to backend directory
      - name: Set up Node.js in backend
        working-directory: ./backend # Assuming the backend is in the "backend" folder
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies for backend
        working-directory: ./backend
        run: npm ci

      - name: Start backend with PM2
        working-directory: ./backend
        run: pm2 restart sohozmeal -a
