name: Build and Deploy Frontend

on:
  push:
    branches:
      - frontend

jobs:
  build-and-deploy:
    runs-on: self-hosted 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Copy dist files to web directory
        run: |
          sudo cp -r dist/* /var/www/naamist/ 
        env:
          NODE_ENV: production
